const itemColors = {
  "IcePlunge": "skyblue",
  "Quikcool": "#ccc",
  "Polar": "lightgreen",
  "Bracer": "orange",
  "VaporBlock": "teal",
  "HeatSafe": "lightcoral",
  "AbsoluteZero": "deepskyblue",
  "PermaFrost": "lightgreen",
  "Artic": "khaki",
  "Boreal": "gray",
  "HeatSink": "coral",
  "Blizzard": "gold",
  "Mercury": "steelblue",

  "Targa": "skyblue",
  "Falco": "#ccc",
  "ForceWall": "lightgreen",
  "AllStop": "orange",
  "Suldrath": "khaki",
  "SecureHyde": "gray",
  "Veil": "teal",
  "Shimmer": "coral",
  "Cloak": "lightcoral",
  "FullStop": "gold",
  "Sukoran": "lightgreen",
  "SecureShield": "gray",
  "Sheut": "deepskyblue",
  "FullBlcock": "steelblue",

  "FoxFire": "skyblue",
  "LightFire": "#ccc",
  "Beacon": "orange",
  "Drift": "teal",
  "SparkFire": "deepskyblue",
  "Yeager": "lightgreen",
  "CrossField": "steelblue",
  "Nova": "purple",
  "Pontes": "gold"
};